version: '3.8'

services:
  # ============================================
  # TRAEFIK (Proxy Reverso & SSL)
  # ============================================
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true" # Dashboard inseguro (solo para ver en 8080 si esta expuesto)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # RedirecciÃ³n HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Certificados Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # Descomentar para pruebas para no quemar cuota
      - "--certificatesresolvers.myresolver.acme.email=tu-email@ejemplo.com" # CAMBIAR ESTO
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_data:/letsencrypt"
    networks:
      - proxy-public
    restart: always

networks:
  proxy-public:
    name: proxy-public
    driver: bridge

volumes:
  traefik_data:
